### ISSUE TITLE
Generated builders missing imports for types in sub-packages of the same module

### ISSUE THREAD

**Issue by tdferreira** [Randgalt/record-builder#275]
## Problem

When a record references types from a sub-package within the same module, the generated builder uses simple (unqualified) type names without adding the corresponding import statements. This causes compilation failures on the generated source files.

## Environment

- record-builder: 52
- Java: 21
- Maven: 3.9.x
- maven-compiler-plugin: 3.15.0
- JavaPoet (Palantir): 0.7.0 (transitive from record-builder-processor)

### Project structure

```
my-module/
├── pom.xml
└── src/main/java/com/example/
    ├── model/
    │   └── MyRecord.java
    └── model/keywrappers/
        └── MyId.java
```

### `pom.xml`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example</groupId>
    <artifactId>record-builder-bug</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.soabase.record-builder</groupId>
            <artifactId>record-builder-core</artifactId>
            <version>52</version>
            <scope>provided</scope>
        </dependency>
        <!-- Adding micrometer-observation 1.17.0 to the classpath triggers the bug -->
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-observation</artifactId>
            <version>1.17.0</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.15.0</version>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>io.soabase.record-builder</groupId>
                            <artifactId>record-builder-processor</artifactId>
                            <version>52</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```

### `src/main/java/com/example/model/keywrappers/MyId.java`

```java
package com.example.model.keywrappers;

public record MyId(int value) {}
```

### `src/main/java/com/example/model/MyRecord.java`

```java
package com.example.model;

import com.example.model.keywrappers.MyId;
import io.soabase.recordbuilder.core.RecordBuilder;

import java.util.Optional;

@RecordBuilder
public record MyRecord(
        MyId id,
        Optional<MyId> parentId
) {}
```

### Steps to reproduce

```bash
mvn clean compile
```

### Expected behavior

The generated `MyRecordBuilder.java` should contain:

```java
import com.example.model.keywrappers.MyId;
```

### Actual behavior

The generated `MyRecordBuilder.java` references `MyId` by simple name without importing it:

```java
package com.example.model;

// No import for MyId

public class MyRecordBuilder {
    private MyId id;           // ERROR: cannot find symbol
    private MyId parentId;     // ERROR: cannot find symbol
    ...
}
```

Compilation fails with:

```
[ERROR] target/generated-sources/annotations/com/example/model/MyRecordBuilder.java:[X,Y] cannot find symbol
  symbol:   class MyId
  location: class com.example.model.MyRecordBuilder
```

## Additional context

- We discovered this when upgrading Spring Boot from 4.0.7 to 4.1.0. Spring Boot 4.1.0 bumps `micrometer-observation` from 1.16.6 to 1.17.0, which is what triggers the issue. Reverting to Spring Boot 4.0.7 (and thus micrometer 1.16.6) resolves the build failure.
- The bug only occurs when certain dependencies are on the classpath (e.g., `micrometer-observation:1.17.0`). With `micrometer-observation:1.16.6` the same code compiles successfully.
- The bug specifically affects types from **sub-packages** of the package where the record is declared. Types from entirely different package hierarchies are imported correctly.
- This suggests that the type resolution logic in the annotation processor treats types in sub-packages as if they were in the same package (and thus don't need imports), but javac disagrees.
- The issue may be in how `javax.lang.model.element.TypeElement` is resolved to a fully-qualified name during code generation, possibly affected by module descriptors or classpath ordering.
